on:
  push:
    tags: 
      - '^[0-9]+./[0-9]+./[0-9]+$'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environments: 
          - prod-a
          - prod-b
    steps:
      - name: "Deploy"
        run: |
          echo "Deploying ${{ github.ref }} to ${{ matrix.environment }}"
    environment: ${{ matrix.environment }}
